/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package undevelopment;

import javax.swing.JTextField;

/**
 *
 * @author eoin0
 */
public class AdaptabilityGUI extends javax.swing.JFrame {

    private String identifiers[];

    /**
     * Creates new form Tabs
     */
    public AdaptabilityGUI() {
        initComponents();
        generateIdentifiers();

        JTextField[][] textFields = new JTextField[8][8]; // 8x8 grid of text fields

        for (char row = 'a'; row <= 'h'; row++) {
            for (int col = 1; col <= 8; col++) {
                int rowIndex = row - 'a'; // 0 to 7
                int colIndex = col - 1;   // 0 to 7

                String identifier = row + String.valueOf(col) + "TF";
                textFields[rowIndex][colIndex] = (JTextField) getContentPane().getComponentByName(identifier);
            }
        }

        String[] crosswordSquares = {
            "a1TF,", "a2TF", "a3TF", "a4TF", "a5TF", "a6TF", "a7TF", "a8TF",
            "b1TF,", "b2TF", "b3TF", "b4TF", "b5TF", "b6TF", "b7TF", "b8TF",
            "c1TF,", "c2TF", "c3TF", "c4TF", "c5TF", "c6TF", "c7TF", "c8TF",
            "d1TF,", "d2TF", "d3TF", "d4TF", "d5TF", "d6TF", "d7TF", "d8TF",
            "e1TF,", "e2TF", "e3TF", "e4TF", "e5TF", "e6TF", "e7TF", "e8TF",
            "f1TF,", "f2TF", "f3TF", "f4TF", "f5TF", "f6TF", "f7TF", "f8TF",
            "g1TF,", "g2TF", "g3TF", "g4TF", "g5TF", "g6TF", "g7TF", "g8TF",
            "h1TF,", "h2TF", "h3TF", "h4TF", "h5TF", "h6TF", "h7TF", "h8TF"
        };

        String[] crosswordSolution = {
            "E", "A", "R", "T", "H", null, null, null,
            "A", null, null, null, "E", "N", "D", null,
            "M", "O", "I", "S", "T", "U", "R", "E",
            "U", null, "N", null, null, null, "A", null,
            "F", null, "D", null, null, null, "I", null,
            "F", "I", "S", "H", null, "O", "N", "E",
            "S", null, null, null, null, null, null, null};

        String[] acrossWords = {"EARTH", "END", "MOISTURE", "FISH", "ONE"};
        String[] downWords = {"EARMUFFS", "HEAT", "WINDS", "RAIN"};

        // Inside your AdaptabilityGUI class, after generating identifiers and crosswordSolution
        // Loop through the crosswordSolution and set values to text fields
        for (int i = 0; i < crosswordSolution.length; i++) {
            String solution = crosswordSolution[i];
            String identifier = identifiers[i];

            // Find the text field corresponding to the identifier
            JTextField textField = findTextField(identifier);

            // If textField is not null and the solution is not null, set the text
            if (textField != null && solution != null) {
                textField.setText(solution);
            }
        }
    }
    // Method to find JTextField by its identifier

    private JTextField findTextField(String identifier) {
        for (java.awt.Component comp : getContentPane().getComponents()) {
            if (comp instanceof JTextField && comp.getName() != null && comp.getName().equals(identifier)) {
                return (JTextField) comp;
            }
        }
        return null; // Return null if not found
    }
// Method to generate identifiers

    private void generateIdentifiers() {
        // Create an array to hold the generated identifiers
        identifiers = new String[64]; // 8 rows * 8 columns

        // Loop through rows (letters a to h)
        for (char row = 'a'; row <= 'h'; row++) {
            // Loop through columns (numbers 1 to 8)
            for (int col = 1; col <= 8; col++) {
                // Create the identifier using the row and column
                String identifier = row + String.valueOf(col) + "TF";
                // Add the identifier to the array
                identifiers[(row - 'a') * 8 + (col - 1)] = identifier;
            }
        }
        // Now you have your identifiers generated in the 'identifiers' array
        // You can use this array as needed within your class

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adaptabilityTab = new javax.swing.JTabbedPane();
        crosswordPanel = new javax.swing.JPanel();
        number5LBL = new javax.swing.JLabel();
        number7LBL = new javax.swing.JLabel();
        number8LBL = new javax.swing.JLabel();
        number6LBL = new javax.swing.JLabel();
        number3LBL = new javax.swing.JLabel();
        number4LBL = new javax.swing.JLabel();
        number2LBL = new javax.swing.JLabel();
        number1LBL = new javax.swing.JLabel();
        a8TF = new javax.swing.JTextField();
        f8TF = new javax.swing.JTextField();
        b8TF = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        clueLabel = new javax.swing.JLabel();
        a1TF = new javax.swing.JTextField();
        b1TF = new javax.swing.JTextField();
        c1TF = new javax.swing.JTextField();
        d1TF = new javax.swing.JTextField();
        a2TF = new javax.swing.JTextField();
        b2TF = new javax.swing.JTextField();
        c2TF = new javax.swing.JTextField();
        d2TF = new javax.swing.JTextField();
        e1TF = new javax.swing.JTextField();
        f1TF = new javax.swing.JTextField();
        g1TF = new javax.swing.JTextField();
        h1TF = new javax.swing.JTextField();
        g2TF = new javax.swing.JTextField();
        h2TF = new javax.swing.JTextField();
        e2TF = new javax.swing.JTextField();
        f2TF = new javax.swing.JTextField();
        c4TF = new javax.swing.JTextField();
        d4TF = new javax.swing.JTextField();
        e3TF = new javax.swing.JTextField();
        a3TF = new javax.swing.JTextField();
        f3TF = new javax.swing.JTextField();
        g3TF = new javax.swing.JTextField();
        b3TF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        h3TF = new javax.swing.JTextField();
        g4TF = new javax.swing.JTextField();
        c3TF = new javax.swing.JTextField();
        h4TF = new javax.swing.JTextField();
        d3TF = new javax.swing.JTextField();
        e4TF = new javax.swing.JTextField();
        a4TF = new javax.swing.JTextField();
        f4TF = new javax.swing.JTextField();
        b4TF = new javax.swing.JTextField();
        c6TF = new javax.swing.JTextField();
        titleLBL = new javax.swing.JLabel();
        d6TF = new javax.swing.JTextField();
        e5TF = new javax.swing.JTextField();
        a5TF = new javax.swing.JTextField();
        f5TF = new javax.swing.JTextField();
        g5TF = new javax.swing.JTextField();
        b5TF = new javax.swing.JTextField();
        h5TF = new javax.swing.JTextField();
        g6TF = new javax.swing.JTextField();
        c5TF = new javax.swing.JTextField();
        h6TF = new javax.swing.JTextField();
        d5TF = new javax.swing.JTextField();
        e6TF = new javax.swing.JTextField();
        a6TF = new javax.swing.JTextField();
        f6TF = new javax.swing.JTextField();
        b6TF = new javax.swing.JTextField();
        c8TF = new javax.swing.JTextField();
        d8TF = new javax.swing.JTextField();
        e7TF = new javax.swing.JTextField();
        a7TF = new javax.swing.JTextField();
        f7TF = new javax.swing.JTextField();
        g7TF = new javax.swing.JTextField();
        b7TF = new javax.swing.JTextField();
        h7TF = new javax.swing.JTextField();
        g8TF = new javax.swing.JTextField();
        c7TF = new javax.swing.JTextField();
        h8TF = new javax.swing.JTextField();
        d7TF = new javax.swing.JTextField();
        e8TF = new javax.swing.JTextField();
        timeLBL = new javax.swing.JLabel();
        hintBTN = new javax.swing.JButton();
        sltnBTN = new javax.swing.JButton();
        solutionPanel = new javax.swing.JPanel();
        crosswordProgress = new javax.swing.JProgressBar();
        clueLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        titleLBL2 = new javax.swing.JLabel();
        backBTN = new javax.swing.JButton();
        number5LBL2 = new javax.swing.JLabel();
        number7LBL2 = new javax.swing.JLabel();
        number8LBL2 = new javax.swing.JLabel();
        number6LBL2 = new javax.swing.JLabel();
        number3LBL2 = new javax.swing.JLabel();
        number4LBL2 = new javax.swing.JLabel();
        number2LBL2 = new javax.swing.JLabel();
        number1LBL2 = new javax.swing.JLabel();
        a8TF1 = new javax.swing.JTextField();
        f8TF1 = new javax.swing.JTextField();
        b8TF1 = new javax.swing.JTextField();
        a1TF1 = new javax.swing.JTextField();
        b1TF1 = new javax.swing.JTextField();
        c1TF1 = new javax.swing.JTextField();
        d1TF1 = new javax.swing.JTextField();
        a2TF1 = new javax.swing.JTextField();
        b2TF1 = new javax.swing.JTextField();
        c2TF1 = new javax.swing.JTextField();
        d2TF1 = new javax.swing.JTextField();
        e1TF1 = new javax.swing.JTextField();
        f1TF1 = new javax.swing.JTextField();
        g1TF1 = new javax.swing.JTextField();
        h1TF1 = new javax.swing.JTextField();
        g2TF1 = new javax.swing.JTextField();
        h2TF1 = new javax.swing.JTextField();
        e2TF1 = new javax.swing.JTextField();
        f2TF1 = new javax.swing.JTextField();
        c4TF1 = new javax.swing.JTextField();
        d4TF1 = new javax.swing.JTextField();
        e3TF1 = new javax.swing.JTextField();
        a3TF1 = new javax.swing.JTextField();
        f3TF1 = new javax.swing.JTextField();
        g3TF1 = new javax.swing.JTextField();
        b3TF1 = new javax.swing.JTextField();
        h3TF1 = new javax.swing.JTextField();
        g4TF1 = new javax.swing.JTextField();
        c3TF1 = new javax.swing.JTextField();
        h4TF1 = new javax.swing.JTextField();
        d3TF1 = new javax.swing.JTextField();
        e4TF1 = new javax.swing.JTextField();
        a4TF1 = new javax.swing.JTextField();
        f4TF1 = new javax.swing.JTextField();
        b4TF1 = new javax.swing.JTextField();
        c6TF1 = new javax.swing.JTextField();
        d6TF1 = new javax.swing.JTextField();
        e5TF1 = new javax.swing.JTextField();
        a5TF1 = new javax.swing.JTextField();
        f5TF1 = new javax.swing.JTextField();
        g5TF1 = new javax.swing.JTextField();
        b5TF1 = new javax.swing.JTextField();
        h5TF1 = new javax.swing.JTextField();
        g6TF1 = new javax.swing.JTextField();
        c5TF1 = new javax.swing.JTextField();
        h6TF1 = new javax.swing.JTextField();
        d5TF1 = new javax.swing.JTextField();
        e6TF1 = new javax.swing.JTextField();
        a6TF1 = new javax.swing.JTextField();
        f6TF1 = new javax.swing.JTextField();
        b6TF1 = new javax.swing.JTextField();
        c8TF1 = new javax.swing.JTextField();
        d8TF1 = new javax.swing.JTextField();
        e7TF1 = new javax.swing.JTextField();
        a7TF1 = new javax.swing.JTextField();
        f7TF1 = new javax.swing.JTextField();
        g7TF1 = new javax.swing.JTextField();
        b7TF1 = new javax.swing.JTextField();
        h7TF1 = new javax.swing.JTextField();
        g8TF1 = new javax.swing.JTextField();
        c7TF1 = new javax.swing.JTextField();
        h8TF1 = new javax.swing.JTextField();
        d7TF1 = new javax.swing.JTextField();
        e8TF1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adaptabilityTab.setBackground(new java.awt.Color(100, 150, 200));
        adaptabilityTab.setForeground(new java.awt.Color(255, 255, 255));

        crosswordPanel.setBackground(new java.awt.Color(100, 150, 200));
        crosswordPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        crosswordPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        crosswordPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        crosswordPanel.setRequestFocusEnabled(false);
        crosswordPanel.setLayout(null);

        number5LBL.setText("5");
        crosswordPanel.add(number5LBL);
        number5LBL.setBounds(8, 270, 10, 16);

        number7LBL.setText("7");
        crosswordPanel.add(number7LBL);
        number7LBL.setBounds(10, 447, 10, 16);

        number8LBL.setText("8");
        crosswordPanel.add(number8LBL);
        number8LBL.setBounds(300, 447, 10, 16);

        number6LBL.setText("6");
        crosswordPanel.add(number6LBL);
        number6LBL.setBounds(357, 270, 10, 16);

        number3LBL.setText("3");
        crosswordPanel.add(number3LBL);
        number3LBL.setBounds(240, 156, 10, 16);

        number4LBL.setText("4");
        crosswordPanel.add(number4LBL);
        number4LBL.setBounds(124, 213, 10, 16);

        number2LBL.setText("2");
        crosswordPanel.add(number2LBL);
        number2LBL.setBounds(240, 100, 10, 16);

        number1LBL.setText("1");
        crosswordPanel.add(number1LBL);
        number1LBL.setBounds(10, 100, 10, 16);

        a8TF.setBackground(new java.awt.Color(0, 0, 0));
        a8TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        a8TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(a8TF);
        a8TF.setBounds(412, 98, 40, 40);

        f8TF.setBackground(new java.awt.Color(0, 0, 0));
        f8TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        f8TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(f8TF);
        f8TF.setBounds(412, 388, 40, 40);

        b8TF.setBackground(new java.awt.Color(0, 0, 0));
        b8TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        b8TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(b8TF);
        b8TF.setBounds(412, 156, 40, 40);

        jProgressBar1.setBackground(new java.awt.Color(100, 200, 100));
        jProgressBar1.setForeground(new java.awt.Color(100, 150, 200));
        jProgressBar1.setToolTipText("Crossword Completion");
        jProgressBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        crosswordPanel.add(jProgressBar1);
        jProgressBar1.setBounds(6, 60, 788, 20);

        clueLabel.setForeground(new java.awt.Color(255, 255, 255));
        clueLabel.setText("Clues");
        crosswordPanel.add(clueLabel);
        clueLabel.setBounds(464, 98, 40, 16);

        a1TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        a1TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a1TF.setToolTipText("");
        crosswordPanel.add(a1TF);
        a1TF.setBounds(6, 98, 40, 40);

        b1TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        b1TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(b1TF);
        b1TF.setBounds(6, 156, 40, 40);

        c1TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        c1TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(c1TF);
        c1TF.setBounds(6, 214, 40, 40);

        d1TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        d1TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(d1TF);
        d1TF.setBounds(6, 272, 40, 40);

        a2TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        a2TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(a2TF);
        a2TF.setBounds(64, 98, 40, 40);

        b2TF.setBackground(new java.awt.Color(0, 0, 0));
        b2TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        b2TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(b2TF);
        b2TF.setBounds(64, 156, 40, 40);

        c2TF.setBackground(new java.awt.Color(0, 0, 0));
        c2TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        c2TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(c2TF);
        c2TF.setBounds(64, 214, 40, 40);

        d2TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        d2TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(d2TF);
        d2TF.setBounds(64, 272, 40, 40);

        e1TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        e1TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(e1TF);
        e1TF.setBounds(6, 330, 40, 40);

        f1TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        f1TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(f1TF);
        f1TF.setBounds(6, 388, 40, 40);

        g1TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        g1TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(g1TF);
        g1TF.setBounds(6, 446, 40, 40);

        h1TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        h1TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(h1TF);
        h1TF.setBounds(6, 504, 40, 40);

        g2TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        g2TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(g2TF);
        g2TF.setBounds(64, 446, 40, 40);

        h2TF.setBackground(new java.awt.Color(0, 0, 0));
        h2TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        h2TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(h2TF);
        h2TF.setBounds(64, 504, 40, 40);

        e2TF.setBackground(new java.awt.Color(0, 0, 0));
        e2TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        e2TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(e2TF);
        e2TF.setBounds(64, 330, 40, 40);

        f2TF.setBackground(new java.awt.Color(0, 0, 0));
        f2TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        f2TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(f2TF);
        f2TF.setBounds(64, 388, 40, 40);

        c4TF.setBackground(new java.awt.Color(0, 0, 0));
        c4TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        c4TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(c4TF);
        c4TF.setBounds(180, 214, 40, 40);

        d4TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        d4TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(d4TF);
        d4TF.setBounds(180, 272, 40, 40);

        e3TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        e3TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(e3TF);
        e3TF.setBounds(122, 330, 40, 40);

        a3TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        a3TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(a3TF);
        a3TF.setBounds(122, 98, 40, 40);

        f3TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        f3TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(f3TF);
        f3TF.setBounds(122, 388, 40, 40);

        g3TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        g3TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(g3TF);
        g3TF.setBounds(122, 446, 40, 40);

        b3TF.setBackground(new java.awt.Color(0, 0, 0));
        b3TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        b3TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(b3TF);
        b3TF.setBounds(122, 156, 40, 40);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Down\n\n1: Something to wear in a blizzard.\n2: Form of energy released in a volcanic eruption.\n4: Reach high speeds in a hurricane\n6: Downpour that can lead to flooding.\n\n\nAcross\n\n1: Our Planet\n3: Times when the sun solar flares into us.\n5: Water on a surface\n7: They end up far within land when a tsunami comes.\n8: The amount of moons we have which control the tides\n\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        crosswordPanel.add(jScrollPane1);
        jScrollPane1.setBounds(464, 132, 330, 412);

        h3TF.setBackground(new java.awt.Color(0, 0, 0));
        h3TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        h3TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(h3TF);
        h3TF.setBounds(122, 504, 40, 40);

        g4TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        g4TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(g4TF);
        g4TF.setBounds(180, 446, 40, 40);

        c3TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        c3TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(c3TF);
        c3TF.setBounds(122, 214, 40, 40);

        h4TF.setBackground(new java.awt.Color(0, 0, 0));
        h4TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        h4TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(h4TF);
        h4TF.setBounds(180, 504, 40, 40);

        d3TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        d3TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(d3TF);
        d3TF.setBounds(122, 272, 40, 40);

        e4TF.setBackground(new java.awt.Color(0, 0, 0));
        e4TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        e4TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(e4TF);
        e4TF.setBounds(180, 330, 40, 40);

        a4TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        a4TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(a4TF);
        a4TF.setBounds(180, 98, 40, 40);

        f4TF.setBackground(new java.awt.Color(0, 0, 0));
        f4TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        f4TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(f4TF);
        f4TF.setBounds(180, 388, 40, 40);

        b4TF.setBackground(new java.awt.Color(0, 0, 0));
        b4TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        b4TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(b4TF);
        b4TF.setBounds(180, 156, 40, 40);

        c6TF.setBackground(new java.awt.Color(0, 0, 0));
        c6TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        c6TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(c6TF);
        c6TF.setBounds(296, 214, 40, 40);

        titleLBL.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(255, 255, 255));
        titleLBL.setText("Crossword Natural Disaster");
        crosswordPanel.add(titleLBL);
        titleLBL.setBounds(185, 6, 430, 48);

        d6TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        d6TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(d6TF);
        d6TF.setBounds(296, 272, 40, 40);

        e5TF.setBackground(new java.awt.Color(0, 0, 0));
        e5TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        e5TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(e5TF);
        e5TF.setBounds(238, 330, 40, 40);

        a5TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        a5TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(a5TF);
        a5TF.setBounds(238, 98, 40, 40);

        f5TF.setBackground(new java.awt.Color(0, 0, 0));
        f5TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        f5TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(f5TF);
        f5TF.setBounds(238, 388, 40, 40);

        g5TF.setBackground(new java.awt.Color(0, 0, 0));
        g5TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        g5TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(g5TF);
        g5TF.setBounds(238, 446, 40, 40);

        b5TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        b5TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(b5TF);
        b5TF.setBounds(238, 156, 40, 40);

        h5TF.setBackground(new java.awt.Color(0, 0, 0));
        h5TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        h5TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(h5TF);
        h5TF.setBounds(238, 504, 40, 40);

        g6TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        g6TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(g6TF);
        g6TF.setBounds(296, 446, 40, 40);

        c5TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        c5TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(c5TF);
        c5TF.setBounds(238, 214, 40, 40);

        h6TF.setBackground(new java.awt.Color(0, 0, 0));
        h6TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        h6TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(h6TF);
        h6TF.setBounds(296, 504, 40, 40);

        d5TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        d5TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(d5TF);
        d5TF.setBounds(238, 272, 40, 40);

        e6TF.setBackground(new java.awt.Color(0, 0, 0));
        e6TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        e6TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(e6TF);
        e6TF.setBounds(296, 330, 40, 40);

        a6TF.setBackground(new java.awt.Color(0, 0, 0));
        a6TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        a6TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(a6TF);
        a6TF.setBounds(296, 98, 40, 40);

        f6TF.setBackground(new java.awt.Color(0, 0, 0));
        f6TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        f6TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(f6TF);
        f6TF.setBounds(296, 388, 40, 40);

        b6TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        b6TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(b6TF);
        b6TF.setBounds(296, 156, 40, 40);

        c8TF.setBackground(new java.awt.Color(0, 0, 0));
        c8TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        c8TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(c8TF);
        c8TF.setBounds(412, 214, 40, 40);

        d8TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        d8TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(d8TF);
        d8TF.setBounds(412, 272, 40, 40);

        e7TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        e7TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(e7TF);
        e7TF.setBounds(354, 330, 40, 40);

        a7TF.setBackground(new java.awt.Color(0, 0, 0));
        a7TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        a7TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(a7TF);
        a7TF.setBounds(354, 98, 40, 40);

        f7TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        f7TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(f7TF);
        f7TF.setBounds(354, 388, 40, 40);

        g7TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        g7TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(g7TF);
        g7TF.setBounds(354, 446, 40, 40);

        b7TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        b7TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(b7TF);
        b7TF.setBounds(354, 156, 40, 40);

        h7TF.setBackground(new java.awt.Color(0, 0, 0));
        h7TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        h7TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(h7TF);
        h7TF.setBounds(354, 504, 40, 40);

        g8TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        g8TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(g8TF);
        g8TF.setBounds(412, 446, 40, 40);

        c7TF.setBackground(new java.awt.Color(0, 0, 0));
        c7TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        c7TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(c7TF);
        c7TF.setBounds(354, 214, 40, 40);

        h8TF.setBackground(new java.awt.Color(0, 0, 0));
        h8TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        h8TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(h8TF);
        h8TF.setBounds(412, 504, 40, 40);

        d7TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        d7TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(d7TF);
        d7TF.setBounds(354, 272, 40, 40);

        e8TF.setBackground(new java.awt.Color(0, 0, 0));
        e8TF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        e8TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crosswordPanel.add(e8TF);
        e8TF.setBounds(412, 330, 40, 40);

        timeLBL.setForeground(new java.awt.Color(255, 255, 255));
        timeLBL.setText("Time Remaining: XX");
        crosswordPanel.add(timeLBL);
        timeLBL.setBounds(670, 100, 120, 16);

        hintBTN.setText("Hint");
        hintBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintBTNActionPerformed(evt);
            }
        });
        crosswordPanel.add(hintBTN);
        hintBTN.setBounds(600, 100, 60, 23);

        sltnBTN.setText("Solution");
        sltnBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sltnBTNActionPerformed(evt);
            }
        });
        crosswordPanel.add(sltnBTN);
        sltnBTN.setBounds(510, 100, 80, 23);

        adaptabilityTab.addTab("Game", crosswordPanel);

        solutionPanel.setBackground(new java.awt.Color(100, 150, 200));
        solutionPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        solutionPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        solutionPanel.setRequestFocusEnabled(false);
        solutionPanel.setLayout(null);

        crosswordProgress.setBackground(new java.awt.Color(100, 200, 100));
        crosswordProgress.setForeground(new java.awt.Color(100, 150, 200));
        crosswordProgress.setToolTipText("Crossword Completion");
        crosswordProgress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        solutionPanel.add(crosswordProgress);
        crosswordProgress.setBounds(6, 60, 788, 20);

        clueLabel1.setForeground(new java.awt.Color(255, 255, 255));
        clueLabel1.setText("Clues");
        solutionPanel.add(clueLabel1);
        clueLabel1.setBounds(464, 98, 40, 16);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Down\n\n1: Something to wear in a blizzard.\n2: Form of energy released in a volcanic eruption.\n4: Reach high speeds in a hurricane\n5: Downpour that can lead to flooding.\n\n\nAcross\n\n1: Our Planet\n3: Times when the sun solar flares into us.\n4: Water on a surface\n6: They end up far within land when a tsunami comes.\n7: The amount of moons we have which control the tides.");
        jScrollPane2.setViewportView(jTextArea2);

        solutionPanel.add(jScrollPane2);
        jScrollPane2.setBounds(464, 132, 330, 412);

        titleLBL2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        titleLBL2.setForeground(new java.awt.Color(255, 255, 255));
        titleLBL2.setText("Crossword Natural Disaster");
        solutionPanel.add(titleLBL2);
        titleLBL2.setBounds(185, 6, 430, 48);

        backBTN.setText("Back");
        solutionPanel.add(backBTN);
        backBTN.setBounds(700, 100, 80, 23);

        number5LBL2.setText("5");
        solutionPanel.add(number5LBL2);
        number5LBL2.setBounds(8, 270, 10, 16);

        number7LBL2.setText("7");
        solutionPanel.add(number7LBL2);
        number7LBL2.setBounds(10, 447, 10, 16);

        number8LBL2.setText("8");
        solutionPanel.add(number8LBL2);
        number8LBL2.setBounds(300, 447, 10, 16);

        number6LBL2.setText("6");
        solutionPanel.add(number6LBL2);
        number6LBL2.setBounds(357, 270, 10, 16);

        number3LBL2.setText("3");
        solutionPanel.add(number3LBL2);
        number3LBL2.setBounds(240, 156, 10, 16);

        number4LBL2.setText("4");
        solutionPanel.add(number4LBL2);
        number4LBL2.setBounds(124, 213, 10, 16);

        number2LBL2.setText("2");
        solutionPanel.add(number2LBL2);
        number2LBL2.setBounds(240, 100, 10, 16);

        number1LBL2.setText("1");
        solutionPanel.add(number1LBL2);
        number1LBL2.setBounds(10, 100, 10, 16);

        a8TF1.setBackground(new java.awt.Color(0, 0, 0));
        a8TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        a8TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(a8TF1);
        a8TF1.setBounds(412, 98, 40, 40);

        f8TF1.setBackground(new java.awt.Color(0, 0, 0));
        f8TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        f8TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(f8TF1);
        f8TF1.setBounds(412, 388, 40, 40);

        b8TF1.setBackground(new java.awt.Color(0, 0, 0));
        b8TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        b8TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(b8TF1);
        b8TF1.setBounds(412, 156, 40, 40);

        a1TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        a1TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a1TF1.setText("E");
        a1TF1.setToolTipText("");
        solutionPanel.add(a1TF1);
        a1TF1.setBounds(6, 98, 40, 40);

        b1TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        b1TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b1TF1.setText("A");
        solutionPanel.add(b1TF1);
        b1TF1.setBounds(6, 156, 40, 40);

        c1TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        c1TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c1TF1.setText("R");
        solutionPanel.add(c1TF1);
        c1TF1.setBounds(6, 214, 40, 40);

        d1TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        d1TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        d1TF1.setText("M");
        solutionPanel.add(d1TF1);
        d1TF1.setBounds(6, 272, 40, 40);

        a2TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        a2TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a2TF1.setText("A");
        solutionPanel.add(a2TF1);
        a2TF1.setBounds(64, 98, 40, 40);

        b2TF1.setBackground(new java.awt.Color(0, 0, 0));
        b2TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        b2TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(b2TF1);
        b2TF1.setBounds(64, 156, 40, 40);

        c2TF1.setBackground(new java.awt.Color(0, 0, 0));
        c2TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        c2TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(c2TF1);
        c2TF1.setBounds(64, 214, 40, 40);

        d2TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        d2TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        d2TF1.setText("O");
        solutionPanel.add(d2TF1);
        d2TF1.setBounds(64, 272, 40, 40);

        e1TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        e1TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e1TF1.setText("U");
        solutionPanel.add(e1TF1);
        e1TF1.setBounds(6, 330, 40, 40);

        f1TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        f1TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        f1TF1.setText("F");
        solutionPanel.add(f1TF1);
        f1TF1.setBounds(6, 388, 40, 40);

        g1TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        g1TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        g1TF1.setText("F");
        solutionPanel.add(g1TF1);
        g1TF1.setBounds(6, 446, 40, 40);

        h1TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        h1TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        h1TF1.setText("S");
        solutionPanel.add(h1TF1);
        h1TF1.setBounds(6, 504, 40, 40);

        g2TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        g2TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        g2TF1.setText("I");
        solutionPanel.add(g2TF1);
        g2TF1.setBounds(64, 446, 40, 40);

        h2TF1.setBackground(new java.awt.Color(0, 0, 0));
        h2TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        h2TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(h2TF1);
        h2TF1.setBounds(64, 504, 40, 40);

        e2TF1.setBackground(new java.awt.Color(0, 0, 0));
        e2TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        e2TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(e2TF1);
        e2TF1.setBounds(64, 330, 40, 40);

        f2TF1.setBackground(new java.awt.Color(0, 0, 0));
        f2TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        f2TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(f2TF1);
        f2TF1.setBounds(64, 388, 40, 40);

        c4TF1.setBackground(new java.awt.Color(0, 0, 0));
        c4TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        c4TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(c4TF1);
        c4TF1.setBounds(180, 214, 40, 40);

        d4TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        d4TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        d4TF1.setText("S");
        solutionPanel.add(d4TF1);
        d4TF1.setBounds(180, 272, 40, 40);

        e3TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        e3TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e3TF1.setText("N");
        solutionPanel.add(e3TF1);
        e3TF1.setBounds(122, 330, 40, 40);

        a3TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        a3TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a3TF1.setText("R");
        solutionPanel.add(a3TF1);
        a3TF1.setBounds(122, 98, 40, 40);

        f3TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        f3TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        f3TF1.setText("D");
        solutionPanel.add(f3TF1);
        f3TF1.setBounds(122, 388, 40, 40);

        g3TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        g3TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        g3TF1.setText("S");
        solutionPanel.add(g3TF1);
        g3TF1.setBounds(122, 446, 40, 40);

        b3TF1.setBackground(new java.awt.Color(0, 0, 0));
        b3TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        b3TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(b3TF1);
        b3TF1.setBounds(122, 156, 40, 40);

        h3TF1.setBackground(new java.awt.Color(0, 0, 0));
        h3TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        h3TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(h3TF1);
        h3TF1.setBounds(122, 504, 40, 40);

        g4TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        g4TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        g4TF1.setText("H");
        solutionPanel.add(g4TF1);
        g4TF1.setBounds(180, 446, 40, 40);

        c3TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        c3TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c3TF1.setText("W");
        solutionPanel.add(c3TF1);
        c3TF1.setBounds(122, 214, 40, 40);

        h4TF1.setBackground(new java.awt.Color(0, 0, 0));
        h4TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        h4TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(h4TF1);
        h4TF1.setBounds(180, 504, 40, 40);

        d3TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        d3TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        d3TF1.setText("I");
        solutionPanel.add(d3TF1);
        d3TF1.setBounds(122, 272, 40, 40);

        e4TF1.setBackground(new java.awt.Color(0, 0, 0));
        e4TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        e4TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(e4TF1);
        e4TF1.setBounds(180, 330, 40, 40);

        a4TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        a4TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a4TF1.setText("T");
        solutionPanel.add(a4TF1);
        a4TF1.setBounds(180, 98, 40, 40);

        f4TF1.setBackground(new java.awt.Color(0, 0, 0));
        f4TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        f4TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(f4TF1);
        f4TF1.setBounds(180, 388, 40, 40);

        b4TF1.setBackground(new java.awt.Color(0, 0, 0));
        b4TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        b4TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(b4TF1);
        b4TF1.setBounds(180, 156, 40, 40);

        c6TF1.setBackground(new java.awt.Color(0, 0, 0));
        c6TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        c6TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(c6TF1);
        c6TF1.setBounds(296, 214, 40, 40);

        d6TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        d6TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        d6TF1.setText("U");
        solutionPanel.add(d6TF1);
        d6TF1.setBounds(296, 272, 40, 40);

        e5TF1.setBackground(new java.awt.Color(0, 0, 0));
        e5TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        e5TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(e5TF1);
        e5TF1.setBounds(238, 330, 40, 40);

        a5TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        a5TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a5TF1.setText("H");
        solutionPanel.add(a5TF1);
        a5TF1.setBounds(238, 98, 40, 40);

        f5TF1.setBackground(new java.awt.Color(0, 0, 0));
        f5TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        f5TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(f5TF1);
        f5TF1.setBounds(238, 388, 40, 40);

        g5TF1.setBackground(new java.awt.Color(0, 0, 0));
        g5TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        g5TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(g5TF1);
        g5TF1.setBounds(238, 446, 40, 40);

        b5TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        b5TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b5TF1.setText("E");
        solutionPanel.add(b5TF1);
        b5TF1.setBounds(238, 156, 40, 40);

        h5TF1.setBackground(new java.awt.Color(0, 0, 0));
        h5TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        h5TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(h5TF1);
        h5TF1.setBounds(238, 504, 40, 40);

        g6TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        g6TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        g6TF1.setText("O");
        solutionPanel.add(g6TF1);
        g6TF1.setBounds(296, 446, 40, 40);

        c5TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        c5TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c5TF1.setText("A");
        solutionPanel.add(c5TF1);
        c5TF1.setBounds(238, 214, 40, 40);

        h6TF1.setBackground(new java.awt.Color(0, 0, 0));
        h6TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        h6TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(h6TF1);
        h6TF1.setBounds(296, 504, 40, 40);

        d5TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        d5TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        d5TF1.setText("T");
        solutionPanel.add(d5TF1);
        d5TF1.setBounds(238, 272, 40, 40);

        e6TF1.setBackground(new java.awt.Color(0, 0, 0));
        e6TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        e6TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(e6TF1);
        e6TF1.setBounds(296, 330, 40, 40);

        a6TF1.setBackground(new java.awt.Color(0, 0, 0));
        a6TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        a6TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(a6TF1);
        a6TF1.setBounds(296, 98, 40, 40);

        f6TF1.setBackground(new java.awt.Color(0, 0, 0));
        f6TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        f6TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(f6TF1);
        f6TF1.setBounds(296, 388, 40, 40);

        b6TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        b6TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b6TF1.setText("N");
        solutionPanel.add(b6TF1);
        b6TF1.setBounds(296, 156, 40, 40);

        c8TF1.setBackground(new java.awt.Color(0, 0, 0));
        c8TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        c8TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(c8TF1);
        c8TF1.setBounds(412, 214, 40, 40);

        d8TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        d8TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        d8TF1.setText("E");
        solutionPanel.add(d8TF1);
        d8TF1.setBounds(412, 272, 40, 40);

        e7TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        e7TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e7TF1.setText("A");
        solutionPanel.add(e7TF1);
        e7TF1.setBounds(354, 330, 40, 40);

        a7TF1.setBackground(new java.awt.Color(0, 0, 0));
        a7TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        a7TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(a7TF1);
        a7TF1.setBounds(354, 98, 40, 40);

        f7TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        f7TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        f7TF1.setText("I");
        solutionPanel.add(f7TF1);
        f7TF1.setBounds(354, 388, 40, 40);

        g7TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        g7TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        g7TF1.setText("N");
        solutionPanel.add(g7TF1);
        g7TF1.setBounds(354, 446, 40, 40);

        b7TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        b7TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b7TF1.setText("D");
        solutionPanel.add(b7TF1);
        b7TF1.setBounds(354, 156, 40, 40);

        h7TF1.setBackground(new java.awt.Color(0, 0, 0));
        h7TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        h7TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(h7TF1);
        h7TF1.setBounds(354, 504, 40, 40);

        g8TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        g8TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        g8TF1.setText("E");
        solutionPanel.add(g8TF1);
        g8TF1.setBounds(412, 446, 40, 40);

        c7TF1.setBackground(new java.awt.Color(0, 0, 0));
        c7TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        c7TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(c7TF1);
        c7TF1.setBounds(354, 214, 40, 40);

        h8TF1.setBackground(new java.awt.Color(0, 0, 0));
        h8TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        h8TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(h8TF1);
        h8TF1.setBounds(412, 504, 40, 40);

        d7TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        d7TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        d7TF1.setText("R");
        solutionPanel.add(d7TF1);
        d7TF1.setBounds(354, 272, 40, 40);

        e8TF1.setBackground(new java.awt.Color(0, 0, 0));
        e8TF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        e8TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        solutionPanel.add(e8TF1);
        e8TF1.setBounds(412, 330, 40, 40);

        adaptabilityTab.addTab("Solution", solutionPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adaptabilityTab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adaptabilityTab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hintBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hintBTNActionPerformed

    private void sltnBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sltnBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sltnBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdaptabilityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdaptabilityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdaptabilityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdaptabilityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdaptabilityGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1TF;
    private javax.swing.JTextField a1TF1;
    private javax.swing.JTextField a2TF;
    private javax.swing.JTextField a2TF1;
    private javax.swing.JTextField a3TF;
    private javax.swing.JTextField a3TF1;
    private javax.swing.JTextField a4TF;
    private javax.swing.JTextField a4TF1;
    private javax.swing.JTextField a5TF;
    private javax.swing.JTextField a5TF1;
    private javax.swing.JTextField a6TF;
    private javax.swing.JTextField a6TF1;
    private javax.swing.JTextField a7TF;
    private javax.swing.JTextField a7TF1;
    private javax.swing.JTextField a8TF;
    private javax.swing.JTextField a8TF1;
    private javax.swing.JTabbedPane adaptabilityTab;
    private javax.swing.JTextField b1TF;
    private javax.swing.JTextField b1TF1;
    private javax.swing.JTextField b2TF;
    private javax.swing.JTextField b2TF1;
    private javax.swing.JTextField b3TF;
    private javax.swing.JTextField b3TF1;
    private javax.swing.JTextField b4TF;
    private javax.swing.JTextField b4TF1;
    private javax.swing.JTextField b5TF;
    private javax.swing.JTextField b5TF1;
    private javax.swing.JTextField b6TF;
    private javax.swing.JTextField b6TF1;
    private javax.swing.JTextField b7TF;
    private javax.swing.JTextField b7TF1;
    private javax.swing.JTextField b8TF;
    private javax.swing.JTextField b8TF1;
    private javax.swing.JButton backBTN;
    private javax.swing.JTextField c1TF;
    private javax.swing.JTextField c1TF1;
    private javax.swing.JTextField c2TF;
    private javax.swing.JTextField c2TF1;
    private javax.swing.JTextField c3TF;
    private javax.swing.JTextField c3TF1;
    private javax.swing.JTextField c4TF;
    private javax.swing.JTextField c4TF1;
    private javax.swing.JTextField c5TF;
    private javax.swing.JTextField c5TF1;
    private javax.swing.JTextField c6TF;
    private javax.swing.JTextField c6TF1;
    private javax.swing.JTextField c7TF;
    private javax.swing.JTextField c7TF1;
    private javax.swing.JTextField c8TF;
    private javax.swing.JTextField c8TF1;
    private javax.swing.JLabel clueLabel;
    private javax.swing.JLabel clueLabel1;
    private javax.swing.JPanel crosswordPanel;
    private javax.swing.JProgressBar crosswordProgress;
    private javax.swing.JTextField d1TF;
    private javax.swing.JTextField d1TF1;
    private javax.swing.JTextField d2TF;
    private javax.swing.JTextField d2TF1;
    private javax.swing.JTextField d3TF;
    private javax.swing.JTextField d3TF1;
    private javax.swing.JTextField d4TF;
    private javax.swing.JTextField d4TF1;
    private javax.swing.JTextField d5TF;
    private javax.swing.JTextField d5TF1;
    private javax.swing.JTextField d6TF;
    private javax.swing.JTextField d6TF1;
    private javax.swing.JTextField d7TF;
    private javax.swing.JTextField d7TF1;
    private javax.swing.JTextField d8TF;
    private javax.swing.JTextField d8TF1;
    private javax.swing.JTextField e1TF;
    private javax.swing.JTextField e1TF1;
    private javax.swing.JTextField e2TF;
    private javax.swing.JTextField e2TF1;
    private javax.swing.JTextField e3TF;
    private javax.swing.JTextField e3TF1;
    private javax.swing.JTextField e4TF;
    private javax.swing.JTextField e4TF1;
    private javax.swing.JTextField e5TF;
    private javax.swing.JTextField e5TF1;
    private javax.swing.JTextField e6TF;
    private javax.swing.JTextField e6TF1;
    private javax.swing.JTextField e7TF;
    private javax.swing.JTextField e7TF1;
    private javax.swing.JTextField e8TF;
    private javax.swing.JTextField e8TF1;
    private javax.swing.JTextField f1TF;
    private javax.swing.JTextField f1TF1;
    private javax.swing.JTextField f2TF;
    private javax.swing.JTextField f2TF1;
    private javax.swing.JTextField f3TF;
    private javax.swing.JTextField f3TF1;
    private javax.swing.JTextField f4TF;
    private javax.swing.JTextField f4TF1;
    private javax.swing.JTextField f5TF;
    private javax.swing.JTextField f5TF1;
    private javax.swing.JTextField f6TF;
    private javax.swing.JTextField f6TF1;
    private javax.swing.JTextField f7TF;
    private javax.swing.JTextField f7TF1;
    private javax.swing.JTextField f8TF;
    private javax.swing.JTextField f8TF1;
    private javax.swing.JTextField g1TF;
    private javax.swing.JTextField g1TF1;
    private javax.swing.JTextField g2TF;
    private javax.swing.JTextField g2TF1;
    private javax.swing.JTextField g3TF;
    private javax.swing.JTextField g3TF1;
    private javax.swing.JTextField g4TF;
    private javax.swing.JTextField g4TF1;
    private javax.swing.JTextField g5TF;
    private javax.swing.JTextField g5TF1;
    private javax.swing.JTextField g6TF;
    private javax.swing.JTextField g6TF1;
    private javax.swing.JTextField g7TF;
    private javax.swing.JTextField g7TF1;
    private javax.swing.JTextField g8TF;
    private javax.swing.JTextField g8TF1;
    private javax.swing.JTextField h1TF;
    private javax.swing.JTextField h1TF1;
    private javax.swing.JTextField h2TF;
    private javax.swing.JTextField h2TF1;
    private javax.swing.JTextField h3TF;
    private javax.swing.JTextField h3TF1;
    private javax.swing.JTextField h4TF;
    private javax.swing.JTextField h4TF1;
    private javax.swing.JTextField h5TF;
    private javax.swing.JTextField h5TF1;
    private javax.swing.JTextField h6TF;
    private javax.swing.JTextField h6TF1;
    private javax.swing.JTextField h7TF;
    private javax.swing.JTextField h7TF1;
    private javax.swing.JTextField h8TF;
    private javax.swing.JTextField h8TF1;
    private javax.swing.JButton hintBTN;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel number1LBL;
    private javax.swing.JLabel number1LBL2;
    private javax.swing.JLabel number2LBL;
    private javax.swing.JLabel number2LBL2;
    private javax.swing.JLabel number3LBL;
    private javax.swing.JLabel number3LBL2;
    private javax.swing.JLabel number4LBL;
    private javax.swing.JLabel number4LBL2;
    private javax.swing.JLabel number5LBL;
    private javax.swing.JLabel number5LBL2;
    private javax.swing.JLabel number6LBL;
    private javax.swing.JLabel number6LBL2;
    private javax.swing.JLabel number7LBL;
    private javax.swing.JLabel number7LBL2;
    private javax.swing.JLabel number8LBL;
    private javax.swing.JLabel number8LBL2;
    private javax.swing.JButton sltnBTN;
    private javax.swing.JPanel solutionPanel;
    private javax.swing.JLabel timeLBL;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JLabel titleLBL2;
    // End of variables declaration//GEN-END:variables
}
