/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package undevelopment;

/**
 *
 * @author eoin0
 */
public class CrosswordGUI extends javax.swing.JFrame {

    /**
     * Creates new form Tabs
     */
    public CrosswordGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        letterTF61 = new javax.swing.JTextField();
        letterTF62 = new javax.swing.JTextField();
        letterTF63 = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        clueLabel = new javax.swing.JLabel();
        letterTF = new javax.swing.JTextField();
        letterTF1 = new javax.swing.JTextField();
        letterTF2 = new javax.swing.JTextField();
        letterTF3 = new javax.swing.JTextField();
        letterTF4 = new javax.swing.JTextField();
        letterTF5 = new javax.swing.JTextField();
        letterTF6 = new javax.swing.JTextField();
        letterTF7 = new javax.swing.JTextField();
        letterTF8 = new javax.swing.JTextField();
        letterTF9 = new javax.swing.JTextField();
        letterTF10 = new javax.swing.JTextField();
        letterTF11 = new javax.swing.JTextField();
        letterTF12 = new javax.swing.JTextField();
        letterTF13 = new javax.swing.JTextField();
        letterTF14 = new javax.swing.JTextField();
        letterTF15 = new javax.swing.JTextField();
        letterTF16 = new javax.swing.JTextField();
        letterTF17 = new javax.swing.JTextField();
        letterTF18 = new javax.swing.JTextField();
        letterTF19 = new javax.swing.JTextField();
        letterTF20 = new javax.swing.JTextField();
        letterTF21 = new javax.swing.JTextField();
        letterTF22 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        letterTF23 = new javax.swing.JTextField();
        letterTF24 = new javax.swing.JTextField();
        letterTF25 = new javax.swing.JTextField();
        letterTF26 = new javax.swing.JTextField();
        letterTF27 = new javax.swing.JTextField();
        letterTF28 = new javax.swing.JTextField();
        letterTF29 = new javax.swing.JTextField();
        letterTF30 = new javax.swing.JTextField();
        letterTF31 = new javax.swing.JTextField();
        letterTF32 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        letterTF33 = new javax.swing.JTextField();
        letterTF34 = new javax.swing.JTextField();
        letterTF35 = new javax.swing.JTextField();
        letterTF36 = new javax.swing.JTextField();
        letterTF37 = new javax.swing.JTextField();
        letterTF38 = new javax.swing.JTextField();
        letterTF39 = new javax.swing.JTextField();
        letterTF40 = new javax.swing.JTextField();
        letterTF41 = new javax.swing.JTextField();
        letterTF42 = new javax.swing.JTextField();
        letterTF43 = new javax.swing.JTextField();
        letterTF44 = new javax.swing.JTextField();
        letterTF45 = new javax.swing.JTextField();
        letterTF46 = new javax.swing.JTextField();
        letterTF47 = new javax.swing.JTextField();
        letterTF48 = new javax.swing.JTextField();
        letterTF49 = new javax.swing.JTextField();
        letterTF50 = new javax.swing.JTextField();
        letterTF51 = new javax.swing.JTextField();
        letterTF52 = new javax.swing.JTextField();
        letterTF53 = new javax.swing.JTextField();
        letterTF54 = new javax.swing.JTextField();
        letterTF55 = new javax.swing.JTextField();
        letterTF56 = new javax.swing.JTextField();
        letterTF57 = new javax.swing.JTextField();
        letterTF58 = new javax.swing.JTextField();
        letterTF59 = new javax.swing.JTextField();
        letterTF60 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setRequestFocusEnabled(false);

        letterTF61.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF61.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF62.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF62.setText("I");

        letterTF63.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF63.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jProgressBar1.setBackground(new java.awt.Color(152, 193, 42));
        jProgressBar1.setForeground(new java.awt.Color(202, 242, 251));
        jProgressBar1.setToolTipText("Crossword Completion");
        jProgressBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        clueLabel.setText("Clues");

        letterTF.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF.setText("E");
        letterTF.setToolTipText("");
        letterTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterTFActionPerformed(evt);
            }
        });

        letterTF1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF1.setText("A");

        letterTF2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF2.setText("R");

        letterTF3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF3.setText("M");

        letterTF4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF4.setText("A");

        letterTF5.setBackground(new java.awt.Color(0, 0, 0));
        letterTF5.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF6.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF7.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF7.setText("O");

        letterTF8.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF8.setText("U");
        letterTF8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterTF8ActionPerformed(evt);
            }
        });

        letterTF9.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF9.setText("F");

        letterTF10.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF10.setText("F");

        letterTF11.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF11.setText("S");

        letterTF12.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF12.setText("I");

        letterTF13.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF13.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF14.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF14.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF15.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF15.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF16.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF16.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF17.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF17.setText("S");
        letterTF17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterTF17ActionPerformed(evt);
            }
        });

        letterTF18.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF18.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF19.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF19.setText("R");

        letterTF20.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF20.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF21.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF21.setText("S");

        letterTF22.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF22.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Down\n\n1: Something to wear in colder winters\n2: The energy of temperature\n4: People who make global warming worse.\n6: Australia\n\nAcross\n\n1: Our Planet\n3: Water on a surface\n5: Swimming Creatures\n6: They're a hoot.");
        jScrollPane1.setViewportView(jTextArea1);

        letterTF23.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF23.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF24.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF24.setText("H");

        letterTF25.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF25.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF26.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF26.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF27.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF27.setText("I");

        letterTF28.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF28.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF29.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF29.setText("T");

        letterTF30.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF30.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF31.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF31.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF32.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF32.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Crossword Climate");

        letterTF33.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF33.setText("U");

        letterTF34.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF34.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF35.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF35.setText("H");

        letterTF36.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF36.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF37.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF37.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF38.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF38.setText("E");

        letterTF39.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF39.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF40.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF40.setText("O");

        letterTF41.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF41.setText("A");

        letterTF42.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF42.setText("Z");

        letterTF43.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF43.setText("T");

        letterTF44.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF44.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF45.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF45.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF46.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF46.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF47.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF47.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF48.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF48.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF49.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF49.setText("E");

        letterTF50.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF50.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF51.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF51.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF52.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF52.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF53.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF53.setText("W");

        letterTF54.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF54.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF55.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF55.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF56.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF56.setText("L");

        letterTF57.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF57.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF58.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF58.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        letterTF59.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF59.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF59.setText("R");
        letterTF59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterTF59ActionPerformed(evt);
            }
        });

        letterTF60.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        letterTF60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letterTF60.setText("V");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letterTF9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letterTF15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letterTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letterTF5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letterTF20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letterTF30, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF28, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letterTF22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letterTF31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letterTF36, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF34, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF37, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF39, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letterTF46, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF44, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF40, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF42, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letterTF38, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF35, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF41, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF43, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letterTF47, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF45, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letterTF52, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF50, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF53, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF55, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letterTF62, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF60, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF56, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF58, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letterTF54, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF51, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF57, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF59, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letterTF63, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF61, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF48, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letterTF49, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(clueLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(letterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(letterTF4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(letterTF8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(letterTF14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(letterTF19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(letterTF29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(letterTF18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(letterTF28, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF30, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(letterTF35, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF38, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF41, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF43, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(letterTF45, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF47, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(letterTF34, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF36, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF37, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF39, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(letterTF44, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF46, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF40, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF42, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(letterTF51, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF54, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF57, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF59, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(letterTF61, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF63, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF48, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF49, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(letterTF50, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF52, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF53, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF55, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(letterTF60, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF62, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF56, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letterTF58, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(clueLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crossword", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void letterTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterTFActionPerformed

    private void letterTF8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterTF8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterTF8ActionPerformed

    private void letterTF17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterTF17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterTF17ActionPerformed

    private void letterTF59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterTF59ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterTF59ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrosswordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrosswordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrosswordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrosswordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrosswordGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clueLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField letterTF;
    private javax.swing.JTextField letterTF1;
    private javax.swing.JTextField letterTF10;
    private javax.swing.JTextField letterTF11;
    private javax.swing.JTextField letterTF12;
    private javax.swing.JTextField letterTF13;
    private javax.swing.JTextField letterTF14;
    private javax.swing.JTextField letterTF15;
    private javax.swing.JTextField letterTF16;
    private javax.swing.JTextField letterTF17;
    private javax.swing.JTextField letterTF18;
    private javax.swing.JTextField letterTF19;
    private javax.swing.JTextField letterTF2;
    private javax.swing.JTextField letterTF20;
    private javax.swing.JTextField letterTF21;
    private javax.swing.JTextField letterTF22;
    private javax.swing.JTextField letterTF23;
    private javax.swing.JTextField letterTF24;
    private javax.swing.JTextField letterTF25;
    private javax.swing.JTextField letterTF26;
    private javax.swing.JTextField letterTF27;
    private javax.swing.JTextField letterTF28;
    private javax.swing.JTextField letterTF29;
    private javax.swing.JTextField letterTF3;
    private javax.swing.JTextField letterTF30;
    private javax.swing.JTextField letterTF31;
    private javax.swing.JTextField letterTF32;
    private javax.swing.JTextField letterTF33;
    private javax.swing.JTextField letterTF34;
    private javax.swing.JTextField letterTF35;
    private javax.swing.JTextField letterTF36;
    private javax.swing.JTextField letterTF37;
    private javax.swing.JTextField letterTF38;
    private javax.swing.JTextField letterTF39;
    private javax.swing.JTextField letterTF4;
    private javax.swing.JTextField letterTF40;
    private javax.swing.JTextField letterTF41;
    private javax.swing.JTextField letterTF42;
    private javax.swing.JTextField letterTF43;
    private javax.swing.JTextField letterTF44;
    private javax.swing.JTextField letterTF45;
    private javax.swing.JTextField letterTF46;
    private javax.swing.JTextField letterTF47;
    private javax.swing.JTextField letterTF48;
    private javax.swing.JTextField letterTF49;
    private javax.swing.JTextField letterTF5;
    private javax.swing.JTextField letterTF50;
    private javax.swing.JTextField letterTF51;
    private javax.swing.JTextField letterTF52;
    private javax.swing.JTextField letterTF53;
    private javax.swing.JTextField letterTF54;
    private javax.swing.JTextField letterTF55;
    private javax.swing.JTextField letterTF56;
    private javax.swing.JTextField letterTF57;
    private javax.swing.JTextField letterTF58;
    private javax.swing.JTextField letterTF59;
    private javax.swing.JTextField letterTF6;
    private javax.swing.JTextField letterTF60;
    private javax.swing.JTextField letterTF61;
    private javax.swing.JTextField letterTF62;
    private javax.swing.JTextField letterTF63;
    private javax.swing.JTextField letterTF7;
    private javax.swing.JTextField letterTF8;
    private javax.swing.JTextField letterTF9;
    // End of variables declaration//GEN-END:variables
}
